---
- name: modify hostname to {{hostname}}
  shell: hostnamectl set-hostname {{hostname}}
  tags:
  - single

- name: add hostname to hosts
  shell: echo "127.0.0.1 {{hostname}}" >> /etc/hosts
  tags:
  - single

- name: start hightf
  shell: nvidia-docker run -d -e SERVER_IP=172.30.81.200 -e CLIENT_IP=172.30.20.164 -e CLIENT_PORT={{item}} --network=host  --name=high_tra{{item}} --restart=always shiwu/hightf:4.1
  with_sequence: start=8091 end=8094 stride=1
  tags:
  - single

- name: init env
  script: init.sh 
  tags:
  - single1

